After manipulating the original data in an older version of the code, it was discovered that rolling sums were not computed correctly, as they mistakenly included the data from the current game. This is not true to how we would be realistically predicting games and it sways the model, so this notebook corrects that error.

If you are using this notebook past version 1.0.0, you do not need to worry about running this notebook, as your data should be fine.

In [1]:
import pandas as pd
import numpy as np

import os
import glob

pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

In [2]:
directory = '/users/blaizelahman/Desktop/CFB Model/Original Data'
pattern = os.path.join(directory, '*model*.csv')

teamFiles = glob.glob(pattern)

teamDict = {}

for file in teamFiles:

    teamDF = pd.read_csv(file)

    if teamDF.shape[0] >= 56:

        # throwing out first 20 rows due to missing rolling_sum data
        teamDF = teamDF.drop(teamDF.index[:20])
        teamDF = teamDF.reset_index(drop = True)
    
        key = teamDF['School'][0]
        teamDict[key] = teamDF
    
        print(f'Added: {key}')

Added: Boston College
Added: Rutgers
Added: Auburn
Added: North Texas
Added: Nebraska
Added: Oklahoma State
Added: Arizona State
Added: Eastern Michigan
Added: Louisiana
Added: Colorado State
Added: Idaho
Added: Illinois
Added: Air Force
Added: Kent State
Added: Louisiana Monroe
Added: Iowa
Added: Akron
Added: Ohio
Added: Georgia
Added: South Alabama
Added: Georgia Tech
Added: Western Kentucky
Added: Maryland
Added: Arizona
Added: Minnesota
Added: Pittsburgh
Added: Marshall
Added: Louisiana Tech
Added: Virginia Tech
Added: California
Added: Georgia Southern
Added: Rice
Added: Missouri
Added: UCF
Added: Kansas State
Added: Appalachian State
Added: Michigan
Added: Clemson
Added: Oregon
Added: Florida Atlantic
Added: Central Michigan
Added: Louisville
Added: Navy
Added: Washington State
Added: Tennessee
Added: Arkansas State
Added: Kansas
Added: Miami
Added: Alabama
Added: Vanderbilt
Added: USC
Added: Indiana
Added: UMass
Added: Utah State
Added: Baylor
Added: Tulsa
Added: Ole Miss
Added: BYU
Added: UTEP
Added: Syracuse
Added: Middle Tennessee
Added: Arkansas
Added: UT San Antonio
Added: Hawai'i
Added: Oregon State
Added: Southern Mississippi
Added: Florida State
Added: Texas A&M
Added: UAB
Added: Boise State
Added: Duke
Added: Colorado
Added: Northern Illinois
Added: Coastal Carolina
Added: Florida
Added: Wyoming
Added: Houston
Added: Cincinnati
Added: New Mexico
Added: Texas Tech
Added: Texas State
Added: Temple
Added: Wisconsin
Added: Purdue
Added: Liberty
Added: East Carolina
Added: Old Dominion
Added: Oklahoma
Added: Toledo
Added: Troy
Added: Ohio State
Added: Penn State
Added: Buffalo
Added: Nevada
Added: Florida International
Added: Iowa State
Added: Northwestern
Added: New Mexico State
Added: South Carolina
Added: Memphis
Added: Western Michigan
Added: Miami (OH)
Added: South Florida
Added: Fresno State
Added: Tulane
Added: NC State
Added: Virginia
Added: Georgia State
Added: Bowling Green
Added: Ball State
Added: Army
Added: UNLV
Added: San José State
Added: Stanford
Added: LSU
Added: Utah
Added: Charlotte
Added: Notre Dame
Added: SMU
Added: UCLA
Added: Washington
Added: Michigan State
Added: Texas
Added: West Virginia
Added: Mississippi State
Added: Connecticut
Added: Kentucky
Added: Wake Forest
Added: North Carolina
Added: San Diego State
Added: TCU

Let's see where we went wrong earlier

In [10]:
teamDict['Florida State']['Points'][-10:]

198    31
199    39
200    41
201    38
202    41
203    24
204    27
205    58
206    24
207    16
Name: Points, dtype: int64

In [11]:
teamDict['Florida State']['rolling_sum_Points8'][-10:]

198    350.0
199    344.0
200    347.0
201    336.0
202    332.0
203    311.0
204    272.0
205    299.0
206    292.0
207    269.0
Name: rolling_sum_Points8, dtype: float64

With how rolling sum is supposed to work, the rolling sum assigned to a game should reflect the sum of a given stat in the previous x games, however we mistakenly included the previous x-1 games plus the current game in that calculation. Let's fix that.

This funciton has been updated to fix the error

In [13]:
def customRollingSum(series, window):
    
    result = []
    
    for i in range(len(series)):
        
        if i < window - 1:
            result.append(np.nan)
            
        else:
            result.append(series[i-window:i].sum(skipna=True))
            
    return pd.Series(result, index=series.index)

In [15]:
for team, teamDF in teamDict.items():

    
    # making rolling sum columns for selected stats for the past 20 and 8 games  
    for games in [20, 8]:
        for column in ['Points','firstDowns','fumblesLost','fumblesRecovered','interceptions','kickReturnYards','kickingPoints','netPassingYards',
                      'passesDeflected', 'passesIntercepted','passingTDs','puntReturns','qbHurries','rushingAttempts','rushingTDs','rushingYards',
                       'sacks','tacklesForLoss','totalFumbles','totalPenaltiesYards','totalYards','turnovers','yardsPerPass','yardsPerRushAttempt', 'totalTDs']:
            newColumn = 'rolling_sum_' + column + str(games) 
            teamDF[newColumn] = customRollingSum(teamDF[column], games)
            
    # altering yardsPerPass and yardsPerRushAttempt columns to reflect their values over the past 20 and 8 games
    teamDF['rolling_sum_yardsPerPass20'] = teamDF['rolling_sum_yardsPerPass20'] / 20
    teamDF['rolling_sum_yardsPerPass8'] = teamDF['rolling_sum_yardsPerPass8'] / 8

    teamDF['rolling_sum_yardsPerRushAttempt20'] = teamDF['rolling_sum_yardsPerRushAttempt20'] / 20
    teamDF['rolling_sum_yardsPerRushAttempt8'] = teamDF['rolling_sum_yardsPerRushAttempt8'] / 8

    teamDict[team] = teamDF
    print(team)

Boston College
Rutgers
Auburn
North Texas
Nebraska
Oklahoma State
Arizona State
Eastern Michigan
Louisiana
Colorado State
Idaho
Illinois
Air Force
Kent State
Louisiana Monroe
Iowa
Akron
Ohio
Georgia
South Alabama
Georgia Tech
Western Kentucky
Maryland
Arizona
Minnesota
Pittsburgh
Marshall
Louisiana Tech
Virginia Tech
California
Georgia Southern
Rice
Missouri
UCF
Kansas State
Appalachian State
Michigan
Clemson
Oregon
Florida Atlantic
Central Michigan
Louisville
Navy
Washington State
Tennessee
Arkansas State
Kansas
Miami
Alabama
Vanderbilt
USC
Indiana
UMass
Utah State
Baylor
Tulsa
Ole Miss
BYU
UTEP
Syracuse
Middle Tennessee
Arkansas
UT San Antonio
Hawai'i
Oregon State
Southern Mississippi
Florida State
Texas A&M
UAB
Boise State
Duke
Colorado
Northern Illinois
Coastal Carolina
Florida
Wyoming
Houston
Cincinnati
New Mexico
Texas Tech
Texas State
Temple
Wisconsin
Purdue
Liberty
East Carolina
Old Dominion
Oklahoma
Toledo
Troy
Ohio State
Penn State
Buffalo
Nevada
Florida International
Iowa State
Northwestern
New Mexico State
South Carolina
Memphis
Western Michigan
Miami (OH)
South Florida
Fresno State
Tulane
NC State
Virginia
Georgia State
Bowling Green
Ball State
Army
UNLV
San José State
Stanford
LSU
Utah
Charlotte
Notre Dame
SMU
UCLA
Washington
Michigan State
Texas
West Virginia
Mississippi State
Connecticut
Kentucky
Wake Forest
North Carolina
San Diego State
TCU

In [16]:
teamDict['Florida State']['Points'][-10:]

198    31
199    39
200    41
201    38
202    41
203    24
204    27
205    58
206    24
207    16
Name: Points, dtype: int64

In [17]:
teamDict['Florida State']['rolling_sum_Points8'][-10:]

198    360.0
199    350.0
200    344.0
201    347.0
202    336.0
203    332.0
204    311.0
205    272.0
206    299.0
207    292.0
Name: rolling_sum_Points8, dtype: float64

Need to fix the "two weeks 1's" issue

In [25]:
teamDict['Florida State'][teamDict['Florida State']['Year'] == 2022][:2]

,Unnamed: 0,Game Id,School,Conference,HomeAway,Points,Week,Year,completionAttempts,defensiveTDs,firstDowns,fourthDownEff,fumblesLost,fumblesRecovered,interceptionTDs,interceptionYards,interceptions,kickReturnTDs,kickReturnYards,kickReturns,kickingPoints,netPassingYards,passesDeflected,passesIntercepted,passingTDs,possessionTime,puntReturnTDs,puntReturnYards,puntReturns,qbHurries,rushingAttempts,rushingTDs,rushingYards,sacks,tackles,tacklesForLoss,thirdDownEff,totalFumbles,totalPenaltiesYards,totalYards,turnovers,yardsPerPass,yardsPerRushAttempt,totalTDs,School_opp,Conference_opp,HomeAway_opp,Points_opp,Week_opp,Year_opp,completionAttempts_opp,defensiveTDs_opp,firstDowns_opp,fourthDownEff_opp,fumblesLost_opp,fumblesRecovered_opp,interceptionTDs_opp,interceptionYards_opp,interceptions_opp,kickReturnTDs_opp,kickReturnYards_opp,kickReturns_opp,kickingPoints_opp,netPassingYards_opp,passesDeflected_opp,passesIntercepted_opp,passingTDs_opp,possessionTime_opp,puntReturnTDs_opp,puntReturnYards_opp,puntReturns_opp,qbHurries_opp,rushingAttempts_opp,rushingTDs_opp,rushingYards_opp,sacks_opp,tackles_opp,tacklesForLoss_opp,thirdDownEff_opp,totalFumbles_opp,totalPenaltiesYards_opp,totalYards_opp,turnovers_opp,yardsPerPass_opp,yardsPerRushAttempt_opp,totalTDs_opp,scoreDiff,pointTotal,Win,rolling_sum_Points20,rolling_sum_firstDowns20,rolling_sum_fumblesLost20,rolling_sum_fumblesRecovered20,rolling_sum_interceptions20,rolling_sum_kickReturnYards20,rolling_sum_kickingPoints20,rolling_sum_netPassingYards20,rolling_sum_passesDeflected20,rolling_sum_passesIntercepted20,rolling_sum_passingTDs20,rolling_sum_puntReturns20,rolling_sum_qbHurries20,rolling_sum_rushingAttempts20,rolling_sum_rushingTDs20,rolling_sum_rushingYards20,rolling_sum_sacks20,rolling_sum_tacklesForLoss20,rolling_sum_totalFumbles20,rolling_sum_totalPenaltiesYards20,rolling_sum_totalYards20,rolling_sum_turnovers20,rolling_sum_yardsPerPass20,rolling_sum_yardsPerRushAttempt20,rolling_sum_totalTDs20,rolling_sum_Points8,rolling_sum_firstDowns8,rolling_sum_fumblesLost8,rolling_sum_fumblesRecovered8,rolling_sum_interceptions8,rolling_sum_kickReturnYards8,rolling_sum_kickingPoints8,rolling_sum_netPassingYards8,rolling_sum_passesDeflected8,rolling_sum_passesIntercepted8,rolling_sum_passingTDs8,rolling_sum_puntReturns8,rolling_sum_qbHurries8,rolling_sum_rushingAttempts8,rolling_sum_rushingTDs8,rolling_sum_rushingYards8,rolling_sum_sacks8,rolling_sum_tacklesForLoss8,rolling_sum_totalFumbles8,rolling_sum_totalPenaltiesYards8,rolling_sum_totalYards8,rolling_sum_turnovers8,rolling_sum_yardsPerPass8,rolling_sum_yardsPerRushAttempt8,rolling_sum_totalTDs8,rolling_sum_Points20_opp,rolling_sum_firstDowns20_opp,rolling_sum_fumblesLost20_opp,rolling_sum_fumblesRecovered20_opp,rolling_sum_interceptions20_opp,rolling_sum_kickReturnYards20_opp,rolling_sum_kickingPoints20_opp,rolling_sum_netPassingYards20_opp,rolling_sum_passesDeflected20_opp,rolling_sum_passesIntercepted20_opp,rolling_sum_passingTDs20_opp,rolling_sum_puntReturns20_opp,rolling_sum_qbHurries20_opp,rolling_sum_rushingAttempts20_opp,rolling_sum_rushingTDs20_opp,rolling_sum_rushingYards20_opp,rolling_sum_sacks20_opp,rolling_sum_tacklesForLoss20_opp,rolling_sum_totalFumbles20_opp,rolling_sum_totalPenaltiesYards20_opp,rolling_sum_totalYards20_opp,rolling_sum_turnovers20_opp,rolling_sum_yardsPerPass20_opp,rolling_sum_yardsPerRushAttempt20_opp,rolling_sum_totalTDs20_opp,rolling_sum_Points8_opp,rolling_sum_firstDowns8_opp,rolling_sum_fumblesLost8_opp,rolling_sum_fumblesRecovered8_opp,rolling_sum_interceptions8_opp,rolling_sum_kickReturnYards8_opp,rolling_sum_kickingPoints8_opp,rolling_sum_netPassingYards8_opp,rolling_sum_passesDeflected8_opp,rolling_sum_passesIntercepted8_opp,rolling_sum_passingTDs8_opp,rolling_sum_puntReturns8_opp,rolling_sum_qbHurries8_opp,rolling_sum_rushingAttempts8_opp,rolling_sum_rushingTDs8_opp,rolling_sum_rushingYards8_opp,rolling_sum_sacks8_opp,rolling_sum_tacklesForLoss8_opp,rolling_sum_totalFumbles8_opp,rolling_sum_totalPenaltiesYards8_opp,rolling_sum_totalYards8_opp,rolling_sum_turnovers8_opp,rolling_sum_yardsPerPass8_opp,rolling_sum_yardsPerRushAttempt8_opp,rolling_sum_totalTDs8_opp
183,813,401403867,Florida State,ACC,home,24,1,2022,20.33,0.0,23.0,0.1,1.0,2.0,NaN,NaN,0.0,0.0,45.0,2.0,6.0,260.0,2.0,NaN,2.0,34.06,0.0,0.0,1.0,0.0,38.0,1.0,132.0,4.0,49.0,6.0,11.17,NaN,6.65,392.0,1.0,7.9,3.5,3.0,LSU,SEC,away,23,1,2022,25.35,0.0,25.0,2.2,2.0,1.0,NaN,NaN,0.0,0.0,31.0,2.0,5.0,209.0,3.0,NaN,2.0,25.54,0.0,0.0,2.0,0.0,30.0,1.0,139.0,2.0,50.0,4.0,5.11,NaN,3.30,348.0,2.0,6.0,4.6,3.0,1,47,True,545.0,395.0,12.0,14.0,19.0,822.0,105.0,4427.0,97.0,18.0,32.0,29.0,65.0,724.0,34.0,3186.0,49.0,137.0,31.0,174.494,7613.0,31.0,7.935,4.325,68.0,239.0,168.0,6.0,5.0,4.0,293.0,49.0,1634.0,28.0,12.0,14.0,12.0,28.0,296.0,15.0,1372.0,20.0,56.0,14.0,55.79,3006.0,10.0,8.425,4.4125,30.0,659.0,456.0,10.0,8.0,12.0,300.0,159.0,5979.0,80.0,17.0,54.0,30.0,56.0,667.0,27.0,2721.0,57.0,149.0,21.0,105.498,8700.0,22.0,8.395,4.365,82.0,191.0,164.0,7.0,2.0,5.0,135.0,47.0,1863.0,23.0,5.0,15.0,14.0,15.0,301.0,8.0,1099.0,20.0,52.0,10.0,34.43,2962.0,12.0,6.8,3.5875,24.0
184,818,401411090,Florida State,ACC,home,47,1,2022,14.22,0.0,33.0,1.2,0.0,0.0,NaN,NaN,1.0,0.0,26.0,2.0,11.0,232.0,5.0,NaN,0.0,35.13,0.0,7.0,2.0,0.0,54.0,6.0,406.0,1.0,21.0,6.0,5.10,1.0,5.55,638.0,1.0,10.5,7.5,6.0,Duquesne,NEC,away,7,1,2022,7.17,0.0,11.0,0.0,0.0,0.0,0.0,50.0,0.0,0.0,54.0,4.0,1.0,71.0,3.0,1.0,1.0,24.47,NaN,NaN,NaN,1.0,30.0,0.0,93.0,1.0,41.0,1.0,1.10,1.0,4.29,164.0,0.0,4.2,3.1,1.0,40,54,True,538.0,396.0,13.0,12.0,19.0,809.0,104.0,4371.0,83.0,18.0,31.0,26.0,63.0,730.0,34.0,3265.0,49.0,131.0,29.0,167.154,7636.0,32.0,7.935,4.415,67.0,230.0,169.0,6.0,7.0,3.0,299.0,46.0,1763.0,27.0,11.0,14.0,9.0,27.0,297.0,14.0,1257.0,23.0,59.0,12.0,59.14,3020.0,9.0,8.900,4.0125,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Can see that our data source labeled week 0 games as the "second week 1 game". Let's correctly label it as a week 0 game.

In [42]:
for team, teamDF in teamDict.items():
    for year in np.unique(teamDF['Year'].values):

        yearDF = teamDF[teamDF['Year'] == year]

        if np.sum(yearDF['Week'].values == 1) > 1:

            teamWeek0 = yearDF.index[0]
            teamWeek1 = yearDF.index[1]

            teamDF.loc[teamWeek0], teamDF.loc[teamWeek1] = teamDF.loc[teamWeek1].copy(), teamDF.loc[teamWeek0].copy()

            teamDF.at[teamWeek0, 'Week'] = 0
            
            print(f'Added week 0 for {team} in year {year}')

Added week 0 for North Texas in year 2022
Added week 0 for Nebraska in year 2021
Added week 0 for Nebraska in year 2022
Added week 0 for Colorado State in year 2017
Added week 0 for Colorado State in year 2018
Added week 0 for Illinois in year 2021
Added week 0 for Illinois in year 2022
Added week 0 for Ohio in year 2023
Added week 0 for Western Kentucky in year 2022
Added week 0 for Louisiana Tech in year 2023
Added week 0 for Rice in year 2018
Added week 0 for Florida Atlantic in year 2022
Added week 0 for Vanderbilt in year 2022
Added week 0 for Vanderbilt in year 2023
Added week 0 for USC in year 2023
Added week 0 for UMass in year 2017
Added week 0 for UMass in year 2018
Added week 0 for UMass in year 2023
Added week 0 for Utah State in year 2022
Added week 0 for BYU in year 2017
Added week 0 for UTEP in year 2021
Added week 0 for UTEP in year 2022
Added week 0 for UTEP in year 2023
Added week 0 for Hawai'i in year 2016
Added week 0 for Hawai'i in year 2017
Added week 0 for Hawai'i in year 2018
Added week 0 for Hawai'i in year 2021
Added week 0 for Hawai'i in year 2022
Added week 0 for Hawai'i in year 2023
Added week 0 for Oregon State in year 2017
Added week 0 for Florida State in year 2022
Added week 0 for Wyoming in year 2018
Added week 0 for Wyoming in year 2022
Added week 0 for Nevada in year 2022
Added week 0 for Florida International in year 2023
Added week 0 for New Mexico State in year 2018
Added week 0 for New Mexico State in year 2021
Added week 0 for New Mexico State in year 2022
Added week 0 for New Mexico State in year 2023
Added week 0 for South Florida in year 2017
Added week 0 for Fresno State in year 2021
Added week 0 for San José State in year 2017
Added week 0 for San José State in year 2021
Added week 0 for San José State in year 2023
Added week 0 for Charlotte in year 2022
Added week 0 for Notre Dame in year 2023
Added week 0 for UCLA in year 2021
Added week 0 for Connecticut in year 2021
Added week 0 for Connecticut in year 2022
Added week 0 for North Carolina in year 2022
Added week 0 for San Diego State in year 2023

In [43]:
teamDict['Florida State'][teamDict['Florida State']['Year'] == 2022][:2]

,Unnamed: 0,Game Id,School,Conference,HomeAway,Points,Week,Year,completionAttempts,defensiveTDs,firstDowns,fourthDownEff,fumblesLost,fumblesRecovered,interceptionTDs,interceptionYards,interceptions,kickReturnTDs,kickReturnYards,kickReturns,kickingPoints,netPassingYards,passesDeflected,passesIntercepted,passingTDs,possessionTime,puntReturnTDs,puntReturnYards,puntReturns,qbHurries,rushingAttempts,rushingTDs,rushingYards,sacks,tackles,tacklesForLoss,thirdDownEff,totalFumbles,totalPenaltiesYards,totalYards,turnovers,yardsPerPass,yardsPerRushAttempt,totalTDs,School_opp,Conference_opp,HomeAway_opp,Points_opp,Week_opp,Year_opp,completionAttempts_opp,defensiveTDs_opp,firstDowns_opp,fourthDownEff_opp,fumblesLost_opp,fumblesRecovered_opp,interceptionTDs_opp,interceptionYards_opp,interceptions_opp,kickReturnTDs_opp,kickReturnYards_opp,kickReturns_opp,kickingPoints_opp,netPassingYards_opp,passesDeflected_opp,passesIntercepted_opp,passingTDs_opp,possessionTime_opp,puntReturnTDs_opp,puntReturnYards_opp,puntReturns_opp,qbHurries_opp,rushingAttempts_opp,rushingTDs_opp,rushingYards_opp,sacks_opp,tackles_opp,tacklesForLoss_opp,thirdDownEff_opp,totalFumbles_opp,totalPenaltiesYards_opp,totalYards_opp,turnovers_opp,yardsPerPass_opp,yardsPerRushAttempt_opp,totalTDs_opp,scoreDiff,pointTotal,Win,rolling_sum_Points20,rolling_sum_firstDowns20,rolling_sum_fumblesLost20,rolling_sum_fumblesRecovered20,rolling_sum_interceptions20,rolling_sum_kickReturnYards20,rolling_sum_kickingPoints20,rolling_sum_netPassingYards20,rolling_sum_passesDeflected20,rolling_sum_passesIntercepted20,rolling_sum_passingTDs20,rolling_sum_puntReturns20,rolling_sum_qbHurries20,rolling_sum_rushingAttempts20,rolling_sum_rushingTDs20,rolling_sum_rushingYards20,rolling_sum_sacks20,rolling_sum_tacklesForLoss20,rolling_sum_totalFumbles20,rolling_sum_totalPenaltiesYards20,rolling_sum_totalYards20,rolling_sum_turnovers20,rolling_sum_yardsPerPass20,rolling_sum_yardsPerRushAttempt20,rolling_sum_totalTDs20,rolling_sum_Points8,rolling_sum_firstDowns8,rolling_sum_fumblesLost8,rolling_sum_fumblesRecovered8,rolling_sum_interceptions8,rolling_sum_kickReturnYards8,rolling_sum_kickingPoints8,rolling_sum_netPassingYards8,rolling_sum_passesDeflected8,rolling_sum_passesIntercepted8,rolling_sum_passingTDs8,rolling_sum_puntReturns8,rolling_sum_qbHurries8,rolling_sum_rushingAttempts8,rolling_sum_rushingTDs8,rolling_sum_rushingYards8,rolling_sum_sacks8,rolling_sum_tacklesForLoss8,rolling_sum_totalFumbles8,rolling_sum_totalPenaltiesYards8,rolling_sum_totalYards8,rolling_sum_turnovers8,rolling_sum_yardsPerPass8,rolling_sum_yardsPerRushAttempt8,rolling_sum_totalTDs8,rolling_sum_Points20_opp,rolling_sum_firstDowns20_opp,rolling_sum_fumblesLost20_opp,rolling_sum_fumblesRecovered20_opp,rolling_sum_interceptions20_opp,rolling_sum_kickReturnYards20_opp,rolling_sum_kickingPoints20_opp,rolling_sum_netPassingYards20_opp,rolling_sum_passesDeflected20_opp,rolling_sum_passesIntercepted20_opp,rolling_sum_passingTDs20_opp,rolling_sum_puntReturns20_opp,rolling_sum_qbHurries20_opp,rolling_sum_rushingAttempts20_opp,rolling_sum_rushingTDs20_opp,rolling_sum_rushingYards20_opp,rolling_sum_sacks20_opp,rolling_sum_tacklesForLoss20_opp,rolling_sum_totalFumbles20_opp,rolling_sum_totalPenaltiesYards20_opp,rolling_sum_totalYards20_opp,rolling_sum_turnovers20_opp,rolling_sum_yardsPerPass20_opp,rolling_sum_yardsPerRushAttempt20_opp,rolling_sum_totalTDs20_opp,rolling_sum_Points8_opp,rolling_sum_firstDowns8_opp,rolling_sum_fumblesLost8_opp,rolling_sum_fumblesRecovered8_opp,rolling_sum_interceptions8_opp,rolling_sum_kickReturnYards8_opp,rolling_sum_kickingPoints8_opp,rolling_sum_netPassingYards8_opp,rolling_sum_passesDeflected8_opp,rolling_sum_passesIntercepted8_opp,rolling_sum_passingTDs8_opp,rolling_sum_puntReturns8_opp,rolling_sum_qbHurries8_opp,rolling_sum_rushingAttempts8_opp,rolling_sum_rushingTDs8_opp,rolling_sum_rushingYards8_opp,rolling_sum_sacks8_opp,rolling_sum_tacklesForLoss8_opp,rolling_sum_totalFumbles8_opp,rolling_sum_totalPenaltiesYards8_opp,rolling_sum_totalYards8_opp,rolling_sum_turnovers8_opp,rolling_sum_yardsPerPass8_opp,rolling_sum_yardsPerRushAttempt8_opp,rolling_sum_totalTDs8_opp
183,818,401411090,Florida State,ACC,home,47,0,2022,14.22,0.0,33.0,1.2,0.0,0.0,NaN,NaN,1.0,0.0,26.0,2.0,11.0,232.0,5.0,NaN,0.0,35.13,0.0,7.0,2.0,0.0,54.0,6.0,406.0,1.0,21.0,6.0,5.10,1.0,5.55,638.0,1.0,10.5,7.5,6.0,Duquesne,NEC,away,7,1,2022,7.17,0.0,11.0,0.0,0.0,0.0,0.0,50.0,0.0,0.0,54.0,4.0,1.0,71.0,3.0,1.0,1.0,24.47,NaN,NaN,NaN,1.0,30.0,0.0,93.0,1.0,41.0,1.0,1.10,1.0,4.29,164.0,0.0,4.2,3.1,1.0,40,54,True,538.0,396.0,13.0,12.0,19.0,809.0,104.0,4371.0,83.0,18.0,31.0,26.0,63.0,730.0,34.0,3265.0,49.0,131.0,29.0,167.154,7636.0,32.0,7.935,4.415,67.0,230.0,169.0,6.0,7.0,3.0,299.0,46.0,1763.0,27.0,11.0,14.0,9.0,27.0,297.0,14.0,1257.0,23.0,59.0,12.0,59.14,3020.0,9.0,8.900,4.0125,29.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,813,401403867,Florida State,ACC,home,24,1,2022,20.33,0.0,23.0,0.1,1.0,2.0,NaN,NaN,0.0,0.0,45.0,2.0,6.0,260.0,2.0,NaN,2.0,34.06,0.0,0.0,1.0,0.0,38.0,1.0,132.0,4.0,49.0,6.0,11.17,NaN,6.65,392.0,1.0,7.9,3.5,3.0,LSU,SEC,away,23,1,2022,25.35,0.0,25.0,2.2,2.0,1.0,NaN,NaN,0.0,0.0,31.0,2.0,5.0,209.0,3.0,NaN,2.0,25.54,0.0,0.0,2.0,0.0,30.0,1.0,139.0,2.0,50.0,4.0,5.11,NaN,3.30,348.0,2.0,6.0,4.6,3.0,1,47,True,545.0,395.0,12.0,14.0,19.0,822.0,105.0,4427.0,97.0,18.0,32.0,29.0,65.0,724.0,34.0,3186.0,49.0,137.0,31.0,174.494,7613.0,31.0,7.935,4.325,68.0,239.0,168.0,6.0,5.0,4.0,293.0,49.0,1634.0,28.0,12.0,14.0,12.0,28.0,296.0,15.0,1372.0,20.0,56.0,14.0,55.79,3006.0,10.0,8.425,4.4125,30.0,659.0,456.0,10.0,8.0,12.0,300.0,159.0,5979.0,80.0,17.0,54.0,30.0,56.0,667.0,27.0,2721.0,57.0,149.0,21.0,105.498,8700.0,22.0,8.395,4.365,82.0,191.0,164.0,7.0,2.0,5.0,135.0,47.0,1863.0,23.0,5.0,15.0,14.0,15.0,301.0,8.0,1099.0,20.0,52.0,10.0,34.43,2962.0,12.0,6.8,3.5875,24.0

We need to add betting data to the data frames now, also from collegefootballdata.com

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait

In [ ]:
# setting the download directory and Chrome settings
directory = "/Users/blaizelahman/Desktop/CFBData"
chromeOptions = webdriver.ChromeOptions()
prefs = {"download.default_directory": directory}
chromeOptions.add_experimental_option("prefs", prefs)

# creating Chrome driver
driver = webdriver.Chrome(service = Service(ChromeDriverManager().install()), options = chromeOptions)

# making a dictionary to hold team talent rankings
bettingDict = {}

# downloading betting data for years 2035-2023 from collegefootballdata.com
for year in range(2013, 2024):

    # skipping 2020 because it has bad data
    if year == 2020: 
        continue
        
    try:
        url = f'https://collegefootballdata.com/exporter/lines?year={year}&seasonType=regular}'
        driver.get(url)
        time.sleep(4) 
            
        # clicking the query button
        query = driver.find_element(By.XPATH, "//button[contains(span/text(), 'Query')]")
        query.click()
        time.sleep(3) 
            
        # clicking the export button
        export = driver.find_element(By.XPATH, "//button[contains(span/text(), 'Export')]")
        export.click()
        time.sleep(3)

        key = str(year)
            
        # grabs files from CFBData folder
        files = os.listdir(directory)
        
        # grab the file paths for all files ending in .csv
        filePaths = [os.path.join(directory, name) for name in files if name.endswith('.csv')]

        # grabbing the most recently made file out of those in paths
        file = max(filePaths, key=os.path.getctime)
            
        # loading csv file
        bettingDict[key] = pd.read_csv(file)

        # deleting the file after it has been added
        os.remove(file)

    except Exception as e:
        print(f'Cannot grab data for {year}. Error: {e}')

    print(f'Successfully grabbed data for {year}')

driver.quit()

We can now see that rolling sums have been calculated as intended and the week 0 issue has been fixed. Let's replace our old faulty data files with these.

In [44]:
files = glob.glob(os.path.join('/users/blaizelahman/Desktop/CFB Model/Original Data', '*'))

for file in files:
        
    try:
            
        os.remove(file)
        print(f"Deleted {file}")
            
    except Exception as e:
        
        print(f"Could not delete {file}: {e}")

Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Boston_College_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Rutgers_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Auburn_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/North_Texas_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Nebraska_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Oklahoma_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Arizona_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Eastern_Michigan_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Louisiana_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Colorado_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Idaho_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Illinois_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Air_Force_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Kent_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Louisiana_Monroe_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Iowa_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Akron_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Ohio_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Georgia_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/South_Alabama_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Georgia_Tech_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Western_Kentucky_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Maryland_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Arizona_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Minnesota_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Pittsburgh_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Marshall_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Louisiana_Tech_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Virginia_Tech_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/California_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Georgia_Southern_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Rice_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Missouri_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/UCF_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Kansas_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Appalachian_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Michigan_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Clemson_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Oregon_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Florida_Atlantic_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Central_Michigan_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Louisville_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Navy_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Washington_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Tennessee_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Arkansas_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Kansas_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Miami_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Alabama_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Vanderbilt_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/USC_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Indiana_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/UMass_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Utah_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Baylor_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Tulsa_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Ole_Miss_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/BYU_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/UTEP_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Syracuse_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Middle_Tennessee_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Arkansas_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/UT_San_Antonio_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Hawai'i_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Oregon_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Southern_Mississippi_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Florida_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Texas_A&M_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/UAB_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Boise_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Duke_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Colorado_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Northern_Illinois_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Coastal_Carolina_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Florida_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Wyoming_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Houston_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Cincinnati_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/New_Mexico_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Texas_Tech_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Texas_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Temple_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Wisconsin_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Purdue_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Liberty_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/East_Carolina_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Old_Dominion_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Oklahoma_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Toledo_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Troy_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Ohio_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Penn_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Buffalo_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Nevada_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Florida_International_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Iowa_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Northwestern_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/New_Mexico_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/South_Carolina_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Memphis_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Western_Michigan_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Miami_(OH)_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/South_Florida_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Fresno_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Tulane_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/NC_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Virginia_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Georgia_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Bowling_Green_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Ball_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Army_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/UNLV_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/San_José_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Stanford_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/LSU_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Utah_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Charlotte_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Notre_Dame_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/SMU_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/UCLA_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Washington_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Michigan_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Texas_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/West_Virginia_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Mississippi_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Connecticut_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Kentucky_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/Wake_Forest_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/North_Carolina_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/San_Diego_State_model.csv
Deleted /users/blaizelahman/Desktop/CFB Model/Original Data/TCU_model.csv

In [46]:
for key, team in teamDict.items():
    if 2023 in team['Year'].values:
        name = key.replace(' ', '_') + '_model.csv'
        path = os.path.join('/users/blaizelahman/Desktop/CFB Model/Original Data', name)
        team.to_csv(path)
        print('CSV: ' + name)

CSV: Boston_College_model.csv
CSV: Rutgers_model.csv
CSV: Auburn_model.csv
CSV: North_Texas_model.csv
CSV: Nebraska_model.csv
CSV: Oklahoma_State_model.csv
CSV: Arizona_State_model.csv
CSV: Eastern_Michigan_model.csv
CSV: Louisiana_model.csv
CSV: Colorado_State_model.csv
CSV: Idaho_model.csv
CSV: Illinois_model.csv
CSV: Air_Force_model.csv
CSV: Kent_State_model.csv
CSV: Louisiana_Monroe_model.csv
CSV: Iowa_model.csv
CSV: Akron_model.csv
CSV: Ohio_model.csv
CSV: Georgia_model.csv
CSV: South_Alabama_model.csv
CSV: Georgia_Tech_model.csv
CSV: Western_Kentucky_model.csv
CSV: Maryland_model.csv
CSV: Arizona_model.csv
CSV: Minnesota_model.csv
CSV: Pittsburgh_model.csv
CSV: Marshall_model.csv
CSV: Louisiana_Tech_model.csv
CSV: Virginia_Tech_model.csv
CSV: California_model.csv
CSV: Georgia_Southern_model.csv
CSV: Rice_model.csv
CSV: Missouri_model.csv
CSV: UCF_model.csv
CSV: Kansas_State_model.csv
CSV: Appalachian_State_model.csv
CSV: Michigan_model.csv
CSV: Clemson_model.csv
CSV: Oregon_model.csv
CSV: Florida_Atlantic_model.csv
CSV: Central_Michigan_model.csv
CSV: Louisville_model.csv
CSV: Navy_model.csv
CSV: Washington_State_model.csv
CSV: Tennessee_model.csv
CSV: Arkansas_State_model.csv
CSV: Kansas_model.csv
CSV: Miami_model.csv
CSV: Alabama_model.csv
CSV: Vanderbilt_model.csv
CSV: USC_model.csv
CSV: Indiana_model.csv
CSV: UMass_model.csv
CSV: Utah_State_model.csv
CSV: Baylor_model.csv
CSV: Tulsa_model.csv
CSV: Ole_Miss_model.csv
CSV: BYU_model.csv
CSV: UTEP_model.csv
CSV: Syracuse_model.csv
CSV: Middle_Tennessee_model.csv
CSV: Arkansas_model.csv
CSV: UT_San_Antonio_model.csv
CSV: Hawai'i_model.csv
CSV: Oregon_State_model.csv
CSV: Southern_Mississippi_model.csv
CSV: Florida_State_model.csv
CSV: Texas_A&M_model.csv
CSV: UAB_model.csv
CSV: Boise_State_model.csv
CSV: Duke_model.csv
CSV: Colorado_model.csv
CSV: Northern_Illinois_model.csv
CSV: Coastal_Carolina_model.csv
CSV: Florida_model.csv
CSV: Wyoming_model.csv
CSV: Houston_model.csv
CSV: Cincinnati_model.csv
CSV: New_Mexico_model.csv
CSV: Texas_Tech_model.csv
CSV: Texas_State_model.csv
CSV: Temple_model.csv
CSV: Wisconsin_model.csv
CSV: Purdue_model.csv
CSV: Liberty_model.csv
CSV: East_Carolina_model.csv
CSV: Old_Dominion_model.csv
CSV: Oklahoma_model.csv
CSV: Toledo_model.csv
CSV: Troy_model.csv
CSV: Ohio_State_model.csv
CSV: Penn_State_model.csv
CSV: Buffalo_model.csv
CSV: Nevada_model.csv
CSV: Florida_International_model.csv
CSV: Iowa_State_model.csv
CSV: Northwestern_model.csv
CSV: New_Mexico_State_model.csv
CSV: South_Carolina_model.csv
CSV: Memphis_model.csv
CSV: Western_Michigan_model.csv
CSV: Miami_(OH)_model.csv
CSV: South_Florida_model.csv
CSV: Fresno_State_model.csv
CSV: Tulane_model.csv
CSV: NC_State_model.csv
CSV: Virginia_model.csv
CSV: Georgia_State_model.csv
CSV: Bowling_Green_model.csv
CSV: Ball_State_model.csv
CSV: Army_model.csv
CSV: UNLV_model.csv
CSV: San_José_State_model.csv
CSV: Stanford_model.csv
CSV: LSU_model.csv
CSV: Utah_model.csv
CSV: Charlotte_model.csv
CSV: Notre_Dame_model.csv
CSV: SMU_model.csv
CSV: UCLA_model.csv
CSV: Washington_model.csv
CSV: Michigan_State_model.csv
CSV: Texas_model.csv
CSV: West_Virginia_model.csv
CSV: Mississippi_State_model.csv
CSV: Connecticut_model.csv
CSV: Kentucky_model.csv
CSV: Wake_Forest_model.csv
CSV: North_Carolina_model.csv
CSV: San_Diego_State_model.csv
CSV: TCU_model.csv

TODO: Aggregate columns: yards allowed, punt return yards per punt, interceptions throw per pass, interceptions caught per opposing pass, fumbles per rush, fumbles caused per opposing rush, offensive penalty yards per play, defensive penalty yards per play, penalties per play, turnovers lost, takeaways, touchdowns per play, touchdowns allowed per play, qb hurries per passing play, sacks per passing play, tfl's per play, PPG, defensive/offensive efficiency and other advanced stats. 

Standardizing columns: total third down efficiency, possesion time percentage, total completion percentage

Can also grab coaching data.